export interface Tool {
  id: string
  name: string
  description: string
  category: string
  slug: string
  icon: string
  keywords: string[]
}

export interface Category {
  id: string
  name: string
  slug: string
  description: string
  icon: string
}

export const categories: Category[] = [
  {
    id: 'texte',
    name: 'Texte',
    slug: 'texte',
    description: 'Outils de manipulation et analyse de texte',
    icon: '📝',
  },
  {
    id: 'developpement',
    name: 'Développement',
    slug: 'developpement',
    description: 'Outils pour développeurs web',
    icon: '💻',
  },
  {
    id: 'images',
    name: 'Images',
    slug: 'images',
    description: 'Outils de traitement d\'images',
    icon: '🖼️',
  },
  {
    id: 'pdf',
    name: 'PDF',
    slug: 'pdf',
    description: 'Éditeur et outils de manipulation PDF',
    icon: '📄',
  },
  {
    id: 'calcul',
    name: 'Calcul & Conversion',
    slug: 'calcul',
    description: 'Calculateurs et convertisseurs',
    icon: '🧮',
  },
  {
    id: 'generateurs',
    name: 'Générateurs',
    slug: 'generateurs',
    description: 'Générateurs de code et contenu',
    icon: '⚡',
  },
  {
    id: 'utilitaires',
    name: 'Utilitaires',
    slug: 'utilitaires',
    description: 'Outils pratiques du quotidien',
    icon: '🔧',
  },
  {
    id: 'seo',
    name: 'SEO & Web',
    slug: 'seo',
    description: 'Outils d\'optimisation et analyse SEO',
    icon: '🔎',
  },
]

export const tools: Tool[] = [
  // Catégorie Texte
  {
    id: 'compteur-mots',
    name: 'Compteur de mots',
    description: 'Comptez les mots, caractères, phrases et paragraphes de votre texte instantanément',
    category: 'texte',
    slug: 'compteur-mots',
    icon: '🔢',
    keywords: ['compteur', 'mots', 'caractères', 'texte', 'analyse', 'compter les mots en ligne', 'compteur de caractères gratuit', 'outil compteur de mots', 'nombre de mots texte', 'calculer nombre caractères'],
  },
  {
    id: 'convertisseur-casse',
    name: 'Convertisseur majuscules/minuscules',
    description: 'Convertissez votre texte en majuscules, minuscules, ou titre',
    category: 'texte',
    slug: 'convertisseur-casse',
    icon: '🔤',
    keywords: ['majuscules', 'minuscules', 'casse', 'texte'],
  },
  {
    id: 'lorem-ipsum',
    name: 'Générateur Lorem Ipsum',
    description: 'Générez du texte Lorem Ipsum pour vos maquettes et tests',
    category: 'texte',
    slug: 'lorem-ipsum',
    icon: '📄',
    keywords: ['lorem', 'ipsum', 'texte', 'placeholder', 'faux texte'],
  },
  {
    id: 'suppression-accents',
    name: 'Suppression des accents',
    description: 'Supprimez les accents et caractères spéciaux de votre texte',
    category: 'texte',
    slug: 'suppression-accents',
    icon: '✂️',
    keywords: ['accents', 'caractères', 'spéciaux', 'normalisation'],
  },
  {
    id: 'inverseur-texte',
    name: 'Inverseur de texte',
    description: 'Inversez l\'ordre des caractères de votre texte',
    category: 'texte',
    slug: 'inverseur-texte',
    icon: '🔄',
    keywords: ['inverser', 'texte', 'reverse', 'miroir'],
  },
  {
    id: 'encodeur-url',
    name: 'Encodeur/Décodeur URL',
    description: 'Encodez ou décodez des URLs pour les rendre compatibles web',
    category: 'texte',
    slug: 'encodeur-url',
    icon: '🔗',
    keywords: ['url', 'encodage', 'décodage', 'percent encoding'],
  },
  {
    id: 'encodeur-base64',
    name: 'Encodeur/Décodeur Base64',
    description: 'Encodez ou décodez du texte en Base64',
    category: 'texte',
    slug: 'encodeur-base64',
    icon: '🔐',
    keywords: ['base64', 'encodage', 'décodage', 'conversion'],
  },
  {
    id: 'generateur-slug',
    name: 'Générateur de slugs URL',
    description: 'Générez des slugs SEO-friendly pour vos URLs',
    category: 'texte',
    slug: 'generateur-slug',
    icon: '🔗',
    keywords: ['slug', 'url', 'seo', 'permalink'],
  },
  {
    id: 'extracteur-emails',
    name: 'Extracteur d\'emails',
    description: 'Extrayez toutes les adresses email d\'un texte',
    category: 'texte',
    slug: 'extracteur-emails',
    icon: '📧',
    keywords: ['email', 'extraction', 'mail', 'adresse'],
  },
  {
    id: 'comparateur-texte',
    name: 'Comparateur de texte',
    description: 'Comparez deux textes et visualisez les différences',
    category: 'texte',
    slug: 'comparateur-texte',
    icon: '⚖️',
    keywords: ['diff', 'comparaison', 'différences', 'texte'],
  },

  // Catégorie Développement
  {
    id: 'formateur-json',
    name: 'Formateur JSON',
    description: 'Formatez et embellissez votre code JSON',
    category: 'developpement',
    slug: 'formateur-json',
    icon: '{ }',
    keywords: ['json', 'format', 'beautify', 'prettier', 'formatter json en ligne', 'embellir json gratuit', 'valider et formater json', 'json beautifier français', 'indenter json'],
  },
  {
    id: 'formateur-sql',
    name: 'Formateur SQL',
    description: 'Formatez vos requêtes SQL pour une meilleure lisibilité',
    category: 'developpement',
    slug: 'formateur-sql',
    icon: '🗄️',
    keywords: ['sql', 'format', 'requête', 'base de données'],
  },
  {
    id: 'formateur-html-css',
    name: 'Formateur HTML/CSS',
    description: 'Formatez votre code HTML et CSS',
    category: 'developpement',
    slug: 'formateur-html-css',
    icon: '🎨',
    keywords: ['html', 'css', 'format', 'beautify'],
  },
  {
    id: 'minificateur',
    name: 'Minificateur JS/CSS/HTML',
    description: 'Minifiez votre code pour réduire sa taille',
    category: 'developpement',
    slug: 'minificateur',
    icon: '📦',
    keywords: ['minify', 'compression', 'optimisation', 'js', 'css'],
  },
  {
    id: 'testeur-regex',
    name: 'Testeur de Regex',
    description: 'Testez et déboguez vos expressions régulières',
    category: 'developpement',
    slug: 'testeur-regex',
    icon: '🔍',
    keywords: ['regex', 'regexp', 'expression régulière', 'test'],
  },
  {
    id: 'generateur-password',
    name: 'Générateur de mots de passe',
    description: 'Générez des mots de passe sécurisés et aléatoires',
    category: 'developpement',
    slug: 'generateur-password',
    icon: '🔒',
    keywords: ['password', 'mot de passe', 'sécurité', 'aléatoire'],
  },
  {
    id: 'generateur-uuid',
    name: 'Générateur d\'UUID',
    description: 'Générez des UUID v4 uniques',
    category: 'developpement',
    slug: 'generateur-uuid',
    icon: '🆔',
    keywords: ['uuid', 'guid', 'identifiant', 'unique'],
  },
  {
    id: 'convertisseur-json-csv',
    name: 'Convertisseur JSON ↔ CSV',
    description: 'Convertissez vos données entre JSON et CSV',
    category: 'developpement',
    slug: 'convertisseur-json-csv',
    icon: '🔄',
    keywords: ['json', 'csv', 'conversion', 'données'],
  },
  {
    id: 'validateur-json',
    name: 'Validateur JSON',
    description: 'Validez la syntaxe de votre JSON',
    category: 'developpement',
    slug: 'validateur-json',
    icon: '✅',
    keywords: ['json', 'validation', 'syntaxe', 'vérification'],
  },
  {
    id: 'decodeur-jwt',
    name: 'Décodeur JWT',
    description: 'Décodez et lisez le contenu de vos tokens JWT',
    category: 'developpement',
    slug: 'decodeur-jwt',
    icon: '🎫',
    keywords: ['jwt', 'token', 'décodage', 'authentication'],
  },

  // Catégorie Images
  {
    id: 'convertisseur-images',
    name: 'Convertisseur d\'images',
    description: 'Convertissez vos images entre PNG, JPG et WebP',
    category: 'images',
    slug: 'convertisseur-images',
    icon: '🖼️',
    keywords: ['image', 'conversion', 'png', 'jpg', 'webp', 'convertir image en ligne gratuit', 'png vers jpg', 'jpg vers webp', 'convertisseur photo gratuit', 'transformer image'],
  },
  {
    id: 'compresseur-images',
    name: 'Compresseur d\'images',
    description: 'Compressez vos images pour réduire leur taille',
    category: 'images',
    slug: 'compresseur-images',
    icon: '🗜️',
    keywords: ['compression', 'image', 'optimisation', 'réduction'],
  },
  {
    id: 'redimensionneur-images',
    name: 'Redimensionneur d\'images',
    description: 'Redimensionnez vos images aux dimensions souhaitées',
    category: 'images',
    slug: 'redimensionneur-images',
    icon: '📐',
    keywords: ['redimensionner', 'resize', 'image', 'dimensions'],
  },
  {
    id: 'generateur-favicon',
    name: 'Générateur de favicon',
    description: 'Générez un favicon depuis une image',
    category: 'images',
    slug: 'generateur-favicon',
    icon: '⭐',
    keywords: ['favicon', 'icon', 'website', 'image'],
  },
  {
    id: 'extracteur-palette',
    name: 'Extracteur de palette',
    description: 'Extrayez les couleurs dominantes d\'une image',
    category: 'images',
    slug: 'extracteur-palette',
    icon: '🎨',
    keywords: ['couleurs', 'palette', 'image', 'extraction'],
  },
  {
    id: 'convertisseur-image-base64',
    name: 'Image vers Base64',
    description: 'Convertissez une image en chaîne Base64',
    category: 'images',
    slug: 'convertisseur-image-base64',
    icon: '🔐',
    keywords: ['image', 'base64', 'conversion', 'data uri'],
  },
  {
    id: 'generateur-placeholder',
    name: 'Générateur de placeholder',
    description: 'Générez des images placeholder personnalisées',
    category: 'images',
    slug: 'generateur-placeholder',
    icon: '🖼️',
    keywords: ['placeholder', 'image', 'mockup', 'test'],
  },

  // Catégorie PDF
  {
    id: 'editeur-pdf',
    name: 'Éditeur PDF',
    description: 'Annotez vos PDF : ajoutez du texte, des formes, des images et dessinez',
    category: 'pdf',
    slug: 'editeur-pdf',
    icon: '✏️',
    keywords: ['pdf', 'éditeur', 'annotation', 'texte', 'dessin', 'formes', 'éditer pdf en ligne gratuit', 'annoter pdf gratuit', 'modifier pdf sans télécharger', 'ajouter texte sur pdf', 'dessiner sur pdf'],
  },
  {
    id: 'fusionner-pdf',
    name: 'Fusionner PDF',
    description: 'Combinez plusieurs fichiers PDF en un seul',
    category: 'pdf',
    slug: 'fusionner-pdf',
    icon: '🔗',
    keywords: ['pdf', 'fusion', 'combiner', 'merge', 'fusionner pdf gratuit en ligne', 'combiner plusieurs pdf', 'joindre fichiers pdf', 'regrouper pdf en un seul', 'assembler pdf'],
  },
  {
    id: 'decouper-pdf',
    name: 'Découper PDF',
    description: 'Extrayez des pages spécifiques de votre PDF',
    category: 'pdf',
    slug: 'decouper-pdf',
    icon: '✂️',
    keywords: ['pdf', 'découper', 'extraire', 'pages', 'split'],
  },
  {
    id: 'compresser-pdf',
    name: 'Compresser PDF',
    description: 'Réduisez la taille de vos fichiers PDF',
    category: 'pdf',
    slug: 'compresser-pdf',
    icon: '🗜️',
    keywords: ['pdf', 'compression', 'réduire', 'taille'],
  },
  {
    id: 'rotation-pdf',
    name: 'Rotation PDF',
    description: 'Faites pivoter les pages de votre PDF',
    category: 'pdf',
    slug: 'rotation-pdf',
    icon: '🔄',
    keywords: ['pdf', 'rotation', 'pivoter', 'orientation'],
  },
  {
    id: 'images-vers-pdf',
    name: 'Images vers PDF',
    description: 'Créez un PDF à partir de vos images',
    category: 'pdf',
    slug: 'images-vers-pdf',
    icon: '📸',
    keywords: ['pdf', 'images', 'conversion', 'créer'],
  },
  {
    id: 'pdf-vers-images',
    name: 'PDF vers Images',
    description: 'Convertissez les pages de votre PDF en images',
    category: 'pdf',
    slug: 'pdf-vers-images',
    icon: '🖼️',
    keywords: ['pdf', 'images', 'conversion', 'png', 'jpg'],
  },

  // Catégorie Calcul & Conversion
  {
    id: 'calculateur-pourcentage',
    name: 'Calculateur de pourcentage',
    description: 'Calculez facilement des pourcentages',
    category: 'calcul',
    slug: 'calculateur-pourcentage',
    icon: '%',
    keywords: ['pourcentage', 'calcul', 'réduction', 'calculer pourcentage en ligne', 'calculatrice pourcentage gratuit', 'comment calculer un pourcentage', 'calculer remise pourcentage', 'outil calcul pourcentage'],
  },
  {
    id: 'convertisseur-unites',
    name: 'Convertisseur d\'unités',
    description: 'Convertissez entre différentes unités de mesure',
    category: 'calcul',
    slug: 'convertisseur-unites',
    icon: '📏',
    keywords: ['conversion', 'unités', 'mesure', 'longueur', 'poids'],
  },
  {
    id: 'convertisseur-tailles',
    name: 'Convertisseur de tailles',
    description: 'Convertissez les tailles de vêtements entre EU, US et UK',
    category: 'calcul',
    slug: 'convertisseur-tailles',
    icon: '👕',
    keywords: ['tailles', 'vêtements', 'conversion', 'eu', 'us', 'uk'],
  },
  {
    id: 'calculateur-tva',
    name: 'Calculateur de TVA',
    description: 'Calculez la TVA et les prix HT/TTC',
    category: 'calcul',
    slug: 'calculateur-tva',
    icon: '💰',
    keywords: ['tva', 'taxe', 'ht', 'ttc', 'prix'],
  },
  {
    id: 'calculateur-salaire',
    name: 'Calculateur salaire brut/net',
    description: 'Convertissez entre salaire brut et net (France)',
    category: 'calcul',
    slug: 'calculateur-salaire',
    icon: '💼',
    keywords: ['salaire', 'brut', 'net', 'france', 'conversion'],
  },
  {
    id: 'convertisseur-devises',
    name: 'Convertisseur de devises',
    description: 'Convertissez entre différentes devises',
    category: 'calcul',
    slug: 'convertisseur-devises',
    icon: '💱',
    keywords: ['devises', 'monnaie', 'conversion', 'euro', 'dollar'],
  },
  {
    id: 'calculateur-age',
    name: 'Calculateur d\'âge',
    description: 'Calculez votre âge exact en années, mois et jours',
    category: 'calcul',
    slug: 'calculateur-age',
    icon: '🎂',
    keywords: ['âge', 'date', 'naissance', 'calcul'],
  },
  {
    id: 'calculateur-dates',
    name: 'Différence entre dates',
    description: 'Calculez la différence entre deux dates',
    category: 'calcul',
    slug: 'calculateur-dates',
    icon: '📅',
    keywords: ['date', 'différence', 'calcul', 'jours'],
  },
  {
    id: 'convertisseur-fuseaux',
    name: 'Convertisseur de fuseaux horaires',
    description: 'Convertissez les heures entre fuseaux horaires',
    category: 'calcul',
    slug: 'convertisseur-fuseaux',
    icon: '🌍',
    keywords: ['fuseau', 'horaire', 'timezone', 'heure', 'conversion'],
  },
  {
    id: 'calculateur-pret',
    name: 'Calculateur de prêt',
    description: 'Calculez les mensualités de votre prêt',
    category: 'calcul',
    slug: 'calculateur-pret',
    icon: '🏦',
    keywords: ['prêt', 'crédit', 'mensualités', 'emprunt', 'calcul'],
  },

  // Catégorie Générateurs
  {
    id: 'generateur-qrcode',
    name: 'Générateur de QR Code',
    description: 'Générez des QR codes personnalisés',
    category: 'generateurs',
    slug: 'generateur-qrcode',
    icon: '📱',
    keywords: ['qr code', 'qrcode', 'générateur', 'code barre', 'créer qr code gratuit', 'générateur qr code en ligne', 'faire un qr code', 'qr code personnalisé gratuit', 'code qr gratuit'],
  },
  {
    id: 'generateur-codebarre',
    name: 'Générateur de code-barres',
    description: 'Générez des codes-barres de différents formats',
    category: 'generateurs',
    slug: 'generateur-codebarre',
    icon: '|||',
    keywords: ['code-barres', 'barcode', 'générateur', 'ean'],
  },
  {
    id: 'generateur-mentions-legales',
    name: 'Générateur de mentions légales',
    description: 'Générez vos mentions légales conformes',
    category: 'generateurs',
    slug: 'generateur-mentions-legales',
    icon: '⚖️',
    keywords: ['mentions légales', 'rgpd', 'légal', 'générateur'],
  },
  {
    id: 'generateur-politique-confidentialite',
    name: 'Politique de confidentialité',
    description: 'Générez votre politique de confidentialité RGPD',
    category: 'generateurs',
    slug: 'generateur-politique-confidentialite',
    icon: '🔒',
    keywords: ['rgpd', 'confidentialité', 'privacy', 'générateur'],
  },
  {
    id: 'generateur-palette-couleurs',
    name: 'Générateur de palettes',
    description: 'Générez des palettes de couleurs harmonieuses',
    category: 'generateurs',
    slug: 'generateur-palette-couleurs',
    icon: '🎨',
    keywords: ['couleurs', 'palette', 'design', 'générateur'],
  },
  {
    id: 'generateur-gradient',
    name: 'Générateur de gradient CSS',
    description: 'Créez des dégradés CSS personnalisés',
    category: 'generateurs',
    slug: 'generateur-gradient',
    icon: '🌈',
    keywords: ['gradient', 'dégradé', 'css', 'générateur'],
  },
  {
    id: 'generateur-box-shadow',
    name: 'Générateur de box-shadow',
    description: 'Créez des ombres CSS personnalisées',
    category: 'generateurs',
    slug: 'generateur-box-shadow',
    icon: '📦',
    keywords: ['box-shadow', 'ombre', 'css', 'générateur'],
  },
  {
    id: 'generateur-noms',
    name: 'Générateur de noms',
    description: 'Générez des noms aléatoires',
    category: 'generateurs',
    slug: 'generateur-noms',
    icon: '👤',
    keywords: ['noms', 'prénoms', 'aléatoire', 'générateur'],
  },

  // Catégorie Utilitaires
  {
    id: 'minuteur',
    name: 'Minuteur / Chronomètre',
    description: 'Minuteur et chronomètre en ligne',
    category: 'utilitaires',
    slug: 'minuteur',
    icon: '⏱️',
    keywords: ['minuteur', 'chronomètre', 'timer', 'temps'],
  },
  {
    id: 'horloge-mondiale',
    name: 'Horloge mondiale',
    description: 'Affichez l\'heure dans différents fuseaux horaires',
    category: 'utilitaires',
    slug: 'horloge-mondiale',
    icon: '🌍',
    keywords: ['horloge', 'heure', 'monde', 'fuseau'],
  },
  {
    id: 'detecteur-ip',
    name: 'Détecteur d\'IP',
    description: 'Découvrez votre adresse IP et infos navigateur',
    category: 'utilitaires',
    slug: 'detecteur-ip',
    icon: '🌐',
    keywords: ['ip', 'adresse', 'navigateur', 'user agent'],
  },
  {
    id: 'test-frappe',
    name: 'Test de vitesse de frappe',
    description: 'Testez votre vitesse de frappe au clavier',
    category: 'utilitaires',
    slug: 'test-frappe',
    icon: '⌨️',
    keywords: ['frappe', 'typing', 'clavier', 'vitesse', 'test'],
  },
  {
    id: 'compteur-rebours',
    name: 'Compteur à rebours',
    description: 'Créez un compteur à rebours personnalisé',
    category: 'utilitaires',
    slug: 'compteur-rebours',
    icon: '⏰',
    keywords: ['compteur', 'rebours', 'countdown', 'timer'],
  },

  // Catégorie SEO & Web
  {
    id: 'previsualisation-serp',
    name: 'Prévisualisation SERP',
    description: 'Prévisualisez votre résultat Google (desktop et mobile) avec compteur de caractères',
    category: 'seo',
    slug: 'previsualisation-serp',
    icon: '🔍',
    keywords: ['serp', 'google', 'preview', 'prévisualisation', 'résultat google', 'snippet', 'title', 'meta description', 'seo preview'],
  },
  {
    id: 'generateur-robots',
    name: 'Générateur robots.txt',
    description: 'Créez votre fichier robots.txt facilement avec interface visuelle',
    category: 'seo',
    slug: 'generateur-robots',
    icon: '🤖',
    keywords: ['robots', 'robots.txt', 'seo', 'crawler', 'indexation', 'sitemap', 'génér ateur robots txt'],
  },
  {
    id: 'verificateur-meta',
    name: 'Vérificateur Title & Meta',
    description: 'Analysez vos balises title et meta description (longueur, mots-clés, optimisation)',
    category: 'seo',
    slug: 'verificateur-meta',
    icon: '✓',
    keywords: ['title', 'meta', 'description', 'seo', 'vérification', 'optimisation', 'balises meta', 'title tag'],
  },
  {
    id: 'generateur-sitemap',
    name: 'Générateur sitemap.xml',
    description: 'Générez un sitemap.xml à partir d\'une liste d\'URLs',
    category: 'seo',
    slug: 'generateur-sitemap',
    icon: '🗺️',
    keywords: ['sitemap', 'xml', 'seo', 'urls', 'indexation', 'google', 'générateur sitemap'],
  },
  {
    id: 'analyseur-onpage',
    name: 'Analyseur On-Page',
    description: 'Analysez le contenu SEO de votre page (H1, mots-clés, densité, structure)',
    category: 'seo',
    slug: 'analyseur-onpage',
    icon: '📊',
    keywords: ['seo', 'on-page', 'analyse', 'h1', 'mots-clés', 'densité', 'optimisation seo'],
  },
]

export function getToolsByCategory(categorySlug: string): Tool[] {
  return tools.filter((tool) => tool.category === categorySlug)
}

export function getToolBySlug(categorySlug: string, toolSlug: string): Tool | undefined {
  return tools.find((tool) => tool.category === categorySlug && tool.slug === toolSlug)
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((cat) => cat.slug === slug)
}
